repos:
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.2.0
  hooks:
    - id: gitleaks

- repo: https://github.com/adrienverge/yamllint
  rev: v1.26.3
  hooks:
    - id: yamllint

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-case-conflict
